name: elliekim
favicon: null
layout_spectrum: 0.347757421201095
typography_spectrum: 0.4085684709716588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6056170044466853
  lightness: 0.3537973400671035
  saturation: 0.9787105813156813
  rhythmicContrast: 0.8605422573164105
purpose: []
